services:
  svc_booking:
    image: ghcr.io/astral-sh/uv:python3.13-alpine
    env_file:
      - ./.secrets/.env
    command: uv run service.py 0.0.0.0:1111
    working_dir: /var/svc_booking
    volumes:
      - ./svc_booking/:/var/svc_booking
      - ./shared/:/var/svc_booking/shared
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - 1111:1111
  
  svc_flight:
    image: ghcr.io/astral-sh/uv:python3.13-alpine
    env_file:
      - ./.secrets/.env
    command: uv run service.py 0.0.0.0:1112
    working_dir: /var/svc_flight
    volumes:
      - ./svc_flight/:/var/svc_flight
      - ./shared/:/var/svc_flight/shared
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - 1112:1112

  svc_payment:
    image: ghcr.io/astral-sh/uv:python3.13-alpine
    env_file:
      - ./.secrets/.env
    command: uv run service.py 0.0.0.0:1114
    working_dir: /var/svc_payment
    volumes:
      - ./svc_payment/:/var/svc_payment
      - ./shared/:/var/svc_payment/shared
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - 1114:1114

  redis:
    image: redis:7.4.2-alpine
    volumes:
      - redis:/data
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  database:
    image: postgres:17.4-alpine3.21
    restart: always
    env_file:
      - ./.secrets/.env
    volumes:
      - database:/var/lib/postgresql/data
      - ./.docker/init_scripts:/docker-entrypoint-initdb.d
    ports:
      - 6543:5432
    expose:
      - 5432

volumes:
  database:
  redis: